name: Update the Quote

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  update-the-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: update-the-quote

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::reticulate
            any::rmarkdown

      - name: Update the quote
        run: Rscript -e 'reticulate::py_install("requests"); rmarkdown::render("README.Rmd")' || true
        continue-on-error: true

      - name: Commit results
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update README.md"
          git push
